### ISSUE TITLE
Setup CI job for Windows and MySQL 8.x

### ISSUE THREAD

**Issue by dveeden** [perl5-dbi/DBD-mysql#359]
GitHub has windows runners, but it looks like MySQL requires a quite old Visual C++ version according to https://dev.mysql.com/doc/c-api/8.0/en/c-api-building-clients.html

**Comment by dveeden** [comment]
I tried this, but that results in msvcrt issues...
```
  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.36
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-suggests
          install-modules: Devel::CheckLib DBI::DBD
      - run: choco install mysql
      - name: Build
        run: |
          perl Makefile.PL --testhost=127.0.0.1 --testuser=root --cflags='-I"C:\tools\mysql\current\include"' --libs='-L"C:\tools\mysql\current\lib" -lmysqlclient'
          gmake
      - name: Test
        run: gmake test
```

**Comment by dveeden** [comment]
In the v4 branch there is `appveyor.yml`, but looks like appveyor doesn't support MySQL 8.0 ( see https://www.appveyor.com/docs/services-databases/#mysql )

```yml
version: 1.0.{build}

services:
  - mysql

install:
  - cinst StrawberryPerl
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V
  - cpan App::cpanminus
  - cpanm -q --showdeps --with-develop --with-suggests . | findstr /v "^perl\>" | cpanm -n
  - cpanm -q -n Devel::CheckLib

build_script:
  - perl Makefile.PL --mysql_config=c:\strawberry\c\bin\mysql_config.bat --testuser=root --testpassword=Password12!

test_script:
  - gmake test
```
